spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agencia
    username: root
    password: root
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
eureka:
  instance:
     prefer-ip-address: true
     
  client:
    fetch-registry: true
    register-whit-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
